C     ##################################################################
C     ############################ FLAGS.H #############################
C     ##################################################################

C     SLH - December 8, 1997 - Removed LEVEL_RDNUCD because the RDNUCD
C     subroutine no longer exists.

C     SLH - January 29, 1996 - Changed LEVEL_RADTRAD to LEVEL_RADCALC

C     Level-of-detail flags for diagnostic output.

      INTEGER
     *   LEVEL_AQUEOUS,
     *   LEVEL_CIN,
     *   LEVEL_COEFFS,
     *   LEVEL_COENUM,
     *   LEVEL_COUT,
     *   LEVEL_DECAY,
     *   LEVEL_DOSES,
     *   LEVEL_EFF_VOL,
     *   LEVEL_ENERGYC,
     *   LEVEL_ENERGYP,
     *   LEVEL_EQUAL,
     *   LEVEL_EXTEDE,
     *   LEVEL_FILTIN,
     *   LEVEL_FOUT,
     *   LEVEL_INITALL,
     *   LEVEL_INVMAT,
     *   LEVEL_LUPC1,
     *   LEVEL_LUPC2,
     *   LEVEL_LUPC3,
     *   LEVEL_LUPL2,
     *   LEVEL_LUPP1,
     *   LEVEL_LUPP2,
     *   LEVEL_MASSTR,
     *   LEVEL_NECSTEPS,
     *   LEVEL_NIFOUT,
     *   LEVEL_NUCLIDE,
     *   LEVEL_OPOOL,
     *   LEVEL_OUTPUT,
     *   LEVEL_PIPIN,
     *   LEVEL_PIPOUT,
     *   LEVEL_PMFOUT,
     *   LEVEL_PRINTOUT,
     *   LEVEL_RADCALC,
     *   LEVEL_RDBWR,
     *   LEVEL_RDINPD,
     *   LEVEL_RD_NIF,
     *   LEVEL_RDPSF,
     *   LEVEL_RDPWR,
     *   LEVEL_RECIRC,
     *   LEVEL_RESIDUE,
     *   LEVEL_RFTBWR,
     *   LEVEL_RFTOUT,
     *   LEVEL_RFTPWR,
     *   LEVEL_SDFOUT,
     *   LEVEL_SORTER,
     *   LEVEL_SOURCE,
     *   LEVEL_SPRY,
     *   LEVEL_STERM,
     *   LEVEL_SUPIN,
     *   LEVEL_SUPOUT,
     *   LEVEL_TSHIFT,
     *   LEVEL_XIVOLC,
     *   LEVEL_XIVOLP,
     *   LEVEL_XNTDEP,
     *   LEVEL_XNUPDT,
     *   LEVEL_ZERODN,
     *   LEVEL_ZRINV

      COMMON / LEVELS /
     *   LEVEL_AQUEOUS,
     *   LEVEL_CIN,
     *   LEVEL_COEFFS,
     *   LEVEL_COENUM,
     *   LEVEL_COUT,
     *   LEVEL_DECAY,
     *   LEVEL_DOSES,
     *   LEVEL_EFF_VOL,
     *   LEVEL_ENERGYC,
     *   LEVEL_ENERGYP,
     *   LEVEL_EQUAL,
     *   LEVEL_EXTEDE,
     *   LEVEL_FILTIN,
     *   LEVEL_FOUT,
     *   LEVEL_INITALL,
     *   LEVEL_INVMAT,
     *   LEVEL_LUPC1,
     *   LEVEL_LUPC2,
     *   LEVEL_LUPC3,
     *   LEVEL_LUPL2,
     *   LEVEL_LUPP1,
     *   LEVEL_LUPP2,
     *   LEVEL_MASSTR,
     *   LEVEL_NECSTEPS,
     *   LEVEL_NIFOUT,
     *   LEVEL_NUCLIDE,
     *   LEVEL_OPOOL,
     *   LEVEL_OUTPUT,
     *   LEVEL_PIPIN,
     *   LEVEL_PIPOUT,
     *   LEVEL_PMFOUT,
     *   LEVEL_PRINTOUT,
     *   LEVEL_RADCALC,
     *   LEVEL_RDBWR,
     *   LEVEL_RDINPD,
     *   LEVEL_RD_NIF,
     *   LEVEL_RDPSF,
     *   LEVEL_RDPWR,
     *   LEVEL_RECIRC,
     *   LEVEL_RESIDUE,
     *   LEVEL_RFTBWR,
     *   LEVEL_RFTOUT,
     *   LEVEL_RFTPWR,
     *   LEVEL_SDFOUT,
     *   LEVEL_SORTER,
     *   LEVEL_SOURCE,
     *   LEVEL_SPRY,
     *   LEVEL_STERM,
     *   LEVEL_SUPIN,
     *   LEVEL_SUPOUT,
     *   LEVEL_TSHIFT,
     *   LEVEL_XIVOLC,
     *   LEVEL_XIVOLP,
     *   LEVEL_XNTDEP,
     *   LEVEL_XNUPDT,
     *   LEVEL_ZERODN,
     *   LEVEL_ZRINV

C     ##################################################################
C     ############################ FLAGS.H #############################
C     ##################################################################
